#!/bin/zsh
# Zinit Installation Check
# ------------------------
# This should run only at login
ZINIT_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/zinit/zinit.git"
if [[ ! -d $ZINIT_HOME ]]; then
  print -P "%F{33} %F{220}Installing Zinit...%f"
  command mkdir -p "$(dirname $ZINIT_HOME)"
  command git clone https://github.com/zdharma-continuum/zinit "$ZINIT_HOME" &&
    print -P "%F{33} %F{34}Installation successful.%f%b" ||
    print -P "%F{160} Installation failed.%f%b"
fi
